# -*- coding: utf-8 -*-
TEAM_NAMES = {
    "Uzbekistan": "涔屽吂鍒厠鏂潶", "Colombia": "鍝ヤ鸡姣斾簹",
    "Haiti": "娴峰湴", "Curacao": "搴撴媺绱?,
    "Cote d'Ivoire": "绉戠壒杩摝", "Ivory Coast": "绉戠壒杩摝",
    "Czechia": "鎹峰厠", "South Africa": "鍗楅潪",
    "Switzerland": "鐟炲＋", "Bosnia-Herzegovina": "娉㈤粦",
    "Canada": "鍔犳嬁澶?, "Qatar": "鍗″灏?,
    "Argentina": "闃挎牴寤?, "Brazil": "宸磋タ",
    "France": "娉曞浗", "Germany": "寰峰浗",
    "England": "鑻辨牸鍏?, "Spain": "瑗跨彮鐗?,
    "Italy": "鎰忓ぇ鍒?, "Netherlands": "鑽峰叞",
    "Portugal": "钁¤悇鐗?, "Belgium": "姣斿埄鏃?,
    "Croatia": "鍏嬬綏鍦颁簹", "Uruguay": "涔屾媺鍦?,
    "Denmark": "涓归害", "Mexico": "澧ㄨタ鍝?,
    "USA": "缇庡浗", "United States": "缇庡浗",
    "Senegal": "濉炲唴鍔犲皵", "Morocco": "鎽╂礇鍝?,
    "Japan": "鏃ユ湰", "South Korea": "闊╁浗",
    "Korea Republic": "闊╁浗", "Iran": "浼婃湕",
    "Saudi Arabia": "娌欑壒闃挎媺浼?, "Australia": "婢冲ぇ鍒╀簹",
    "Poland": "娉㈠叞", "Serbia": "濉炲皵缁翠簹",
    "Cameroon": "鍠€楹﹂殕", "Ecuador": "鍘勭摐澶氬皵",
    "Ghana": "鍔犵撼", "Tunisia": "绐佸凹鏂?,
    "Costa Rica": "鍝ユ柉杈鹃粠鍔?, "Nigeria": "灏兼棩鍒╀簹",
    "Chile": "鏅哄埄", "Sweden": "鐟炲吀",
    "Turkey": "鍦熻€冲叾", "Austria": "濂ュ湴鍒?,
    "Scotland": "鑻忔牸鍏?, "Norway": "鎸▉",
    "Greece": "甯岃厞", "Russia": "淇勭綏鏂?,
    "Ukraine": "涔屽厠鍏?, "Algeria": "闃垮皵鍙婂埄浜?,
    "Panama": "宸存嬁椹?, "Jamaica": "鐗欎拱鍔?,
    "Paraguay": "宸存媺鍦?, "New Zealand": "鏂拌タ鍏?,
    "China": "涓浗", "India": "鍗板害",
    "Peru": "绉橀瞾", "Venezuela": "濮斿唴鐟炴媺",
    "Bolivia": "鐜诲埄缁翠簹", "Egypt": "鍩冨強",
    "Arsenal": "闃挎．绾?, "Tottenham Hotspur": "鐑埡",
    "Manchester United": "鏇艰仈", "Manchester City": "鏇煎煄",
    "Liverpool": "鍒╃墿娴?, "Chelsea": "鍒囧皵瑗?,
    "Newcastle United": "绾藉崱鏂皵鑱?, "West Ham United": "瑗挎眽濮嗚仈",
    "Crystal Palace": "姘存櫠瀹?, "Everton": "鍩冨紬椤?,
    "Aston Villa": "闃挎柉椤跨淮鎷?, "Brighton & Hove Albion": "甯冭幈椤?,
    "Real Madrid": "鐨囧椹痉閲?, "Barcelona": "宸村缃楅偅",
    "Atletico Madrid": "椹痉閲岀珵鎶€", "Sevilla": "濉炵淮鍒╀簹",
    "Bayern Munich": "鎷滀粊鎱曞凹榛?, "Borussia Dortmund": "澶氱壒钂欏痉",
    "RB Leipzig": "鑾辨瘮閿＄孩鐗?, "Bayer Leverkusen": "鍕掓矁搴撴．",
    "Juventus": "灏ゆ枃鍥炬柉", "AC Milan": "AC绫冲叞",
    "Inter Milan": "鍥介檯绫冲叞", "Napoli": "閭ｄ笉鍕掓柉",
    "AS Roma": "缃楅┈", "Lazio": "鎷夐綈濂?,
    "PSG": "宸撮粠鍦ｆ棩鑰虫浖", "Paris Saint-Germain": "宸撮粠鍦ｆ棩鑰虫浖",
    "Ajax": "闃胯淳鍏嬫柉", "Benfica": "鏈彶鍗?, "Porto": "娉㈠皵鍥?,
}

def translate(name):
    return TEAM_NAMES.get(name, name)
